<?php

if (!defined('ABSPATH')) {
    exit; // tela branca caso o plugin for acessado direto
}

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class NoCopy
{
    private $no_copy_options;

    public function __construct()
    {
        add_action('admin_menu', array( $this, 'no_copy_add_plugin_page' ));
        add_action('admin_init', array( $this, 'no_copy_page_init' ));
    }

    public function no_copy_add_plugin_page()
    {
        add_options_page(
            'No copy', // page_title
            'No copy', // menu_title
            'manage_options', // capability
            'no-copy', // menu_slug
            array( $this, 'no_copy_create_admin_page' ) // function
        );
    }

    public function no_copy_create_admin_page()
    {
        $this->no_copy_options = get_option('no_copy_option_name'); ?>

        <div class="wrap">
        <h1>Your site is protected!</h1>
                <ul>
                    <li>✔ Disable copy of text</li>
                    <li>✔ Disable right mouse click</li>
                    <li>✔ Disable print screen</li>
                    <li>✔ Disable print to PDF</li>
                    <li>✔ Disable Ctrl+U (view source)</li>
                    <li>✔ Disable Ctrl+P (Print)</li>
                    <li>✔ Disable Print with printer</li>
                    <li>✔ Disable Ctrl+S (Save page)</li>
                    <li>✔ Disable Ctrl+C</li>
                    <li>✔ Disable Ctrl+v</li>
                </ul>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <hr/>
                <?php
                    settings_fields('no_copy_option_group');
                    do_settings_sections('no-copy-admin');
                    submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function no_copy_page_init()
    {
        register_setting(
            'no_copy_option_group', // option_group
            'no_copy_option_name', // option_name
            array( $this, 'no_copy_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'no_copy_setting_section', // id
            'Debug', // title
            array( $this, 'no_copy_section_info' ), // callback
            'no-copy-admin' // page
        );

        add_settings_field(
            'disable_all_copy_protections_0', // id
            'Disable all copy protections.', // title
            array( $this, 'disable_all_copy_protections_0_callback' ), // callback
            'no-copy-admin', // page
            'no_copy_setting_section' // section
        );
    }

    public function no_copy_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['disable_all_copy_protections_0'])) {
            $sanitary_values['disable_all_copy_protections_0'] = $input['disable_all_copy_protections_0'];
        }

        return $sanitary_values;
    }

    public function no_copy_section_info()
    {
    }

    public function disable_all_copy_protections_0_callback()
    {
        printf(
            '<input type="checkbox" name="no_copy_option_name[disable_all_copy_protections_0]" id="disable_all_copy_protections_0" value="disable_all_copy_protections_0" %s>',
            ( isset($this->no_copy_options['disable_all_copy_protections_0']) && $this->no_copy_options['disable_all_copy_protections_0'] === 'disable_all_copy_protections_0' ) ? 'checked' : ''
        );
    }
}
if (is_admin()) {
    $no_copy = new NoCopy();
}

/*
 * Retrieve this value with:
 * $no_copy_options = get_option( 'no_copy_option_name' ); // Array of All Options
 * $disable_all_copy_protections_0 = $no_copy_options['disable_all_copy_protections_0']; // Disable all copy protections.
 */
